// Boot-time Tier 1 integrity check.
//
// Reads core.manifest.sha256 (generated by scripts/build-core-manifest.mjs at
// release time, committed to the clean repo) and verifies every listed file
// against its sha256. Any mismatch is logged and surfaced via writeTamperFlag
// so admins can see it in the update panel.
//
// This is detection, not prevention. Combined with the agent tool-whitelist
// (lib/user-claude.ts only allows WebFetch/WebSearch/Read), agents cannot
// modify core files in the first place. This catches the rare case where
// something else on the box did.

import { createHash } from "crypto";
import fs from "fs";
import path from "path";

const MANIFEST_FILE = path.join(process.cwd(), "core.manifest.sha256");
const FLAG_FILE = path.join(process.cwd(), "data", ".core-tamper.json");

export type TamperReport = {
  ok: boolean;
  checkedAt: string;
  mismatches: string[];
  missing: string[];
  fileCount: number;
};

export function verifyCoreIntegrity(): TamperReport {
  const report: TamperReport = {
    ok: true,
    checkedAt: new Date().toISOString(),
    mismatches: [],
    missing: [],
    fileCount: 0,
  };
  if (!fs.existsSync(MANIFEST_FILE)) {
    return report;
  }
  let manifest: { files: Record<string, string> };
  try {
    manifest = JSON.parse(fs.readFileSync(MANIFEST_FILE, "utf8"));
  } catch {
    return report;
  }
  report.fileCount = Object.keys(manifest.files || {}).length;
  for (const [file, expected] of Object.entries(manifest.files || {})) {
    const full = path.join(process.cwd(), file);
    if (!fs.existsSync(full)) { report.missing.push(file); continue; }
    try {
      const buf = fs.readFileSync(full);
      const actual = createHash("sha256").update(buf).digest("hex");
      if (actual !== expected) report.mismatches.push(file);
    } catch {
      report.missing.push(file);
    }
  }
  report.ok = report.mismatches.length === 0 && report.missing.length === 0;

  try {
    fs.mkdirSync(path.dirname(FLAG_FILE), { recursive: true });
    if (report.ok) {
      if (fs.existsSync(FLAG_FILE)) fs.unlinkSync(FLAG_FILE);
    } else {
      fs.writeFileSync(FLAG_FILE, JSON.stringify(report, null, 2));
    }
  } catch { /* non-fatal */ }

  if (!report.ok) {
    console.warn(`[core-integrity] TAMPER DETECTED — ${report.mismatches.length} mismatched, ${report.missing.length} missing`);
    for (const f of report.mismatches.slice(0, 10)) console.warn(`  mismatch: ${f}`);
    for (const f of report.missing.slice(0, 5)) console.warn(`  missing:  ${f}`);
  }
  return report;
}

export function readTamperFlag(): TamperReport | null {
  try {
    if (!fs.existsSync(FLAG_FILE)) return null;
    return JSON.parse(fs.readFileSync(FLAG_FILE, "utf8"));
  } catch {
    return null;
  }
}
